//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietDonHang()
        {
            this.DanhGiaSanPhams = new HashSet<DanhGiaSanPham>();
        }
    
        public int MaCTDH { get; set; }
        public int MaDonHang { get; set; }
        public decimal ThanhTien { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public int MaBienThe { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual DonHang DonHang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public virtual DonHang DonHang1 { get; set; }
    }
}
