//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.KhieuNais = new HashSet<KhieuNai>();
        }
    
        public int MaDonHang { get; set; }
        public int MaDVVC { get; set; }
        public decimal TongTien { get; set; }
        public string TrangThaiVanChuyen { get; set; }
        public string TrangThaiDonHang { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string GhiChu { get; set; }
        public bool TrangThaiThanhToan { get; set; }
        public System.DateTime ThoiGianDat { get; set; }
        public Nullable<int> MaGiamGia { get; set; }
        public int MaNguoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DonViVanChuyen DonViVanChuyen { get; set; }
        public virtual GiamGia GiamGia { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhieuNai> KhieuNais { get; set; }
    }
}
