//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiamGia()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaGiamGia { get; set; }
        public string TenMaGG { get; set; }
        public string MoTa { get; set; }
        public decimal GiaTriDonHangToiThieu { get; set; }
        public decimal GiaTriGiamToiDa { get; set; }
        public Nullable<double> GiaTriGiam { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
