//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECommerceWebsiteEntities : DbContext
    {
        public ECommerceWebsiteEntities()
            : base("name=ECommerceWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnhSanPham> AnhSanPhams { get; set; }
        public virtual DbSet<BienTheSanPham> BienTheSanPhams { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual DbSet<CuaHang> CuaHangs { get; set; }
        public virtual DbSet<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<DonViVanChuyen> DonViVanChuyens { get; set; }
        public virtual DbSet<GiamGia> GiamGias { get; set; }
        public virtual DbSet<GioHang> GioHangs { get; set; }
        public virtual DbSet<KhieuNai> KhieuNais { get; set; }
        public virtual DbSet<NguoiBan> NguoiBans { get; set; }
        public virtual DbSet<NguoiMua> NguoiMuas { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        [DbFunction("ECommerceWebsiteEntities", "fn_LayDanhGiaSanPham")]
        public virtual IQueryable<fn_LayDanhGiaSanPham_Result> fn_LayDanhGiaSanPham(Nullable<int> maSanPham)
        {
            var maSanPhamParameter = maSanPham.HasValue ?
                new ObjectParameter("MaSanPham", maSanPham) :
                new ObjectParameter("MaSanPham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_LayDanhGiaSanPham_Result>("[ECommerceWebsiteEntities].[fn_LayDanhGiaSanPham](@MaSanPham)", maSanPhamParameter);
        }
    }
}
