//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Seller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSanPham
    {
        public int MaDG { get; set; }
        public int MaCTDH { get; set; }
        public int SoSao { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        //public virtual NguoiMua NguoiMua { get; set; }

    }
}
