//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public ChiTietDonHang()
        {
            this.DanhGiaSanPhams = new HashSet<DanhGiaSanPham>();
        }
    
        public int MaCTDH { get; set; }
        public int MaDonHang { get; set; }
        public int MaCTGH { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual ChiTietGioHang ChiTietGioHang { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
    }
}
