//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang
    {
        public CuaHang()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaCuaHang { get; set; }
        public int MaNguoiBan { get; set; }
        public string TenCuaHang { get; set; }
        public string HinhAnh { get; set; }
        public string DiaChi { get; set; }
    
        public virtual NguoiBan NguoiBan { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
