//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViVanChuyen
    {
        public DonViVanChuyen()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaDVVC { get; set; }
        public string TenDVVC { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
