//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        public GiamGia()
        {
            this.DatHangs = new HashSet<DatHang>();
        }
    
        public int MaGiamGia { get; set; }
        public string TenMaGG { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> GiaTriDonHangToiThieu { get; set; }
        public Nullable<double> GiaTriGiamToiDa { get; set; }
        public Nullable<double> GiaTriGiam { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
    
        public virtual ICollection<DatHang> DatHangs { get; set; }
    }
}
