//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhieuNai
    {
        public int MaKN { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string HinhAnh { get; set; }
        public int MaDonHang { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
