//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.CuaHangs = new HashSet<CuaHang>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MaNguoiDung { get; set; }
        public string Email { get; set; }
        public string HoVaTen { get; set; }
        public string SDT { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string CCCD { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public string HinhAnh { get; set; }
        public bool VaiTro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuaHang> CuaHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
    }
}
