//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiBan
    {
        public NguoiBan()
        {
            this.CuaHangs = new HashSet<CuaHang>();
        }
    
        public int MaNguoiBan { get; set; }
        public string Email { get; set; }
        public string HoVaTen { get; set; }
        public string SDT { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string CCCD { get; set; }
    
        public virtual ICollection<CuaHang> CuaHangs { get; set; }
    }
}
