//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECommerceWebsiteEntities : DbContext
    {
        public ECommerceWebsiteEntities()
            : base("name=ECommerceWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnhSanPham> AnhSanPhams { get; set; }
        public DbSet<BienTheSanPham> BienTheSanPhams { get; set; }
        public DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public DbSet<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public DbSet<CuaHang> CuaHangs { get; set; }
        public DbSet<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public DbSet<DanhMuc> DanhMucs { get; set; }
        public DbSet<DatHang> DatHangs { get; set; }
        public DbSet<DonHang> DonHangs { get; set; }
        public DbSet<DonViVanChuyen> DonViVanChuyens { get; set; }
        public DbSet<GiamGia> GiamGias { get; set; }
        public DbSet<GioHang> GioHangs { get; set; }
        public DbSet<KhieuNai> KhieuNais { get; set; }
        public DbSet<NguoiBan> NguoiBans { get; set; }
        public DbSet<NguoiMua> NguoiMuas { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
