//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteMVC_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.AnhSanPhams = new HashSet<AnhSanPham>();
            this.BienTheSanPhams = new HashSet<BienTheSanPham>();
            this.KhieuNais = new HashSet<KhieuNai>();
        }
    
        public int MaSanPham { get; set; }
        public int MaDanhMuc { get; set; }
        public int MaCuaHang { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public string LoaiPhanLoai { get; set; }
    
        public virtual ICollection<AnhSanPham> AnhSanPhams { get; set; }
        public virtual ICollection<BienTheSanPham> BienTheSanPhams { get; set; }
        public virtual CuaHang CuaHang { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<KhieuNai> KhieuNais { get; set; }
    }
}
